apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cormorant-virtual-service
  namespace: cormorant-namespace
spec:
  hosts:
    - cormorant.drewpy.pro
  gateways:
    - istio-system/ingress-gateway
  http:
      - route:
        - destination:
            host: cormorant
            port:
              number: 80